import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "./providers/ToastProvider";
import ReduxProvider from "./providers/ReduxProvider";
import HeaderWrapper from "@/components/layout/HeaderWrapped";
import ClientInit from "@/components/ClientInit";
import ChatDockProvider from "./providers/ChatDockProvider";
import { MessagePriorityProvider } from "@/context/messagePriority/messagePriorityProvider";
import { SocketWrapped } from "./providers/SocketWrapped";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SocketWrapped>
            <ToastProvider />

            <ClientInit>

              <MessagePriorityProvider>
                <ChatDockProvider>
                  <HeaderWrapper />
                  <main className="pt-16 flex flex-col h-screen overflow-hidden">
                    <div className="flex-1 overflow-y-auto custom-scroll">
                      {children}
                    </div>
                  </main>
                </ChatDockProvider>
              </MessagePriorityProvider>
            </ClientInit>
          </SocketWrapped>
        </ReduxProvider>
      </body>
    </html>
  );
}
